### PR TITLE
Revert "chore: update telemetry components"

### PR DESCRIPTION
**Pull request by helio-frota**
This reverts commit b478c44582575a479421c57fe82b5ce4f630e085.

* `cargo build` works inside `trustd` dir, but not from workspace root https://gist.github.com/helio-frota/07c753afd5dceb4d65be14509798de9e
* For some reason it works with github actions https://github.com/trustification/trustify/pull/521#issuecomment-2218330154
* Able to build when commenting this line https://github.com/trustification/trustify/blob/main/server/src/lib.rs#L253
  * Comment from @jcrossley3: 
  > commit introduced some threshold that you stopped hitting when you commented out that line, but i'm not sure that's enough

### CODE REVIEW

**Comment by ctron** [comment]
As neither me, nor the CI experiences that issue. I am not sure simply reverting that PR is the right approach.

One thing that might be worth trying (and maybe you already did) is a `cargo clean`. 

If it doesn't, then I think that simply following the instructions, raising that limit, makes sense. Indeed we are using a lot of macros, and that limit is a safeguard from Rust to not run into infinite macro recursions. However, if there's a need, then it is ok to raise that limit.

**Review by ctron — CHANGES_REQUESTED** [review]
Let's try finding the cause for this and fixing it.

**Comment by jcrossley3** [comment]
> As neither me, nor the CI experiences that issue. I am not sure simply reverting that PR is the right approach.

CI doesn't run `cargo build`. Did you? Breaks for me and @helio-frota every time.

**Comment by jcrossley3** [comment]
> Let's try finding the cause for this and fixing it.

Sure, but why not do that *before* breaking the build?!?! Why update to a pre-release, anyway? What feature were we missing?

Let's revert this so we don't hold up others while trying to figure out why a pre-release dep broke our build?

**Comment by helio-frota** [comment]
so folks I closed the temporary fix and we end up with revert or increase the limit.
then I decided to merge :sunglasses: 
in case problems we can re-re-revert or something, git supports that :+1:

**Review by jcrossley3 — APPROVED** [review]

**Pull request merged**
