### PR TITLE
fix: ensure order using primary keys, not hardcoded id fields

### LINKED ISSUE #267: "filtering" requires an 'id' field
I ran into the issue of:

```
Error: query syntax error: Entity missing Id field
```

* It would be helpful if there would be the name of the entity that's missing that field.
* Why is that required?

### PR DESCRIPTION
**Pull request by jcrossley3**
Fixes #267

All columns in composite keys will be added to the statement if not already present.

### CODE REVIEW

**Review by bobmcwhirter — APPROVED** [review]
I await `else_matters`

**Comment by bobmcwhirter** [comment]
Is it easy enough for me to provide a default sort per entity in our Service, if not user-provided?

**Comment by jcrossley3** [comment]
> I await `else_matters`

Took me a second. Thanks for noticing. It was funnier when I was comparing `actual` to a string. Maybe I'll go back to that for the entertainment value.

**Comment by jcrossley3** [comment]
> Is it easy enough for me to provide a default sort per entity in our Service, if not user-provided?

I don't know. I would expect the UI to drive the ordering.

**Comment by jcrossley3** [comment]
> Is it easy enough for me to provide a default sort per entity in our Service, if not user-provided?

I might've misunderstood your question. You can certainly add an `.order_by` to your statement prior to calling `.filtering`. There are tests ensuring that `.filtering` doesn't muck with existing ordering in the statement and doesn't add redundant ordering. I'm always scared by potential performance impacts of being cavalier with ORDER BY clauses.

**Pull request merged**
