### PR TITLE
chore(ai): endpoint improvements.

### PR DESCRIPTION
**Pull request by chirino**
* Move more of the resource info out of the system messages/prefix into the Tools descriptions
* Disable the product-info tool for now, it’s better to use the sbom-info for similar information.
* Bump async-openai version
* switch to new langchain-rust patch branch
* Add more info to tool response.

### CODE REVIEW

**Review by ctron — APPROVED** [review]
I think this is good in general. I noticed the use of some Red Hat specific/preferred terms (RHEL, quarkus). Maybe there's a better way dealing with this.

**Comment by helio-frota** [comment]
@chirino that is sorta nit and not required :+1: ...

as you already wrote tests for this feature could you please double check with 
`cargo clippy -- -W clippy::redundant_clone` ? not required but, if you can a void a clone, that means you avoided a memory allocation ... as my noob perspective my only safe/backup/shield thing is the test when I call `cargo clippy -- -W clippy::redundant_clone` nowadays :+1:

**Comment by chirino** [comment]
> @chirino that is sorta nit and not required 👍 ...
> 
> as you already wrote tests for this feature could you please double check with `cargo clippy -- -W clippy::redundant_clone` ? not required but, if you can a void a clone, that means you avoided a memory allocation ... as my noob perspective my only safe/backup/shield thing is the test when I call `cargo clippy -- -W clippy::redundant_clone` nowadays 👍

Then we should add that to `cargo xtask precommit` and ci bits so that it consistently gets enforced.

**Comment by chirino** [comment]
> I think this is good in general. I noticed the use of some Red Hat specific/preferred terms (RHEL, quarkus). Maybe there's a better way dealing with this.

Could do.  Just need different example product names.

**Pull request merged**
