### PR TITLE
Push swagger-ui to /swagger-ui and make rapidoc the default UI at /op…

### PR DESCRIPTION
**Pull request by bobmcwhirter**
…enapi/.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Unsure how to verify the OIDC redirect target ish is right.

**Comment by ctron** [comment]
Removing SwaggerUI isn't an option at this point in time: https://github.com/trustification/trustify/issues/578#issuecomment-2247855986

**Review by ctron — CHANGES_REQUESTED** [review]
OAuth2 support in rapidoc is currently broken: https://github.com/trustification/trustify/issues/578#issuecomment-2247855986

**Comment by bobmcwhirter** [comment]
Ah, damnit. I'll put swagger back in.

**Comment by bobmcwhirter** [comment]
Any opinions on this fork? https://github.com/Authress-Engineering/openapi-explorer?tab=readme-ov-file#openapi-explorer

**Comment by bobmcwhirter** [comment]
> Removing SwaggerUI isn't an option at this point in time: [#578 (comment)](https://github.com/trustification/trustify/issues/578#issuecomment-2247855986)

Add swagger-ui back (and it's tests) at /swagger-ui/ with the pretty UI at /openapi/ with the hope that it'll improve.

**Review by ctron — APPROVED** [review]

**Pull request merged**
