### PR TITLE
Include more details in product-details endpoint.

### LINKED ISSUE #538: /api/v1/product contains list of versions but /api/v1/product/{id} does not
If I do `GET /api/v1/product` I get a response similar to:

```json
{
  "items": [
    {
      "id": "d1287b2c-5902-47d9-9ff4-84f00de5d23b",
      "name": "ubi7-container",
      "versions": [
        {
          "id": "057276eb-bbe1-48a4-8604-480f8c32294f",
          "version": "7.9-1042",
          "sbom_id": "0190a20f-213e-7751-8138-f117f85aef79"
        },
        {
          "id": "e16ff780-28e9-4304-b51c-7c70c1be29fb",
          "version": "7.9-1057",
          "sbom_id": "0190a20e-8ad1-71a2-bc00-5054f154e40f"
        },
      ],
      "vendor": {
        "id": "8bbbdd1f-e332-4db6-8112-dd70ba84e9df",
        "name": "Organization: Red Hat"
      }
    }
  ],
  "total": 274
}
```

But if I fetch a single product using `GET /api/v1/product/{id}` then I get this response:

```json
{
   "id":"d1287b2c-5902-47d9-9ff4-84f00de5d23b",
   "name":"ubi7-container"
}
```

You can see that it does not contain the `versions` field.

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Fixes #538.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
note: the included `id` are now `urn:uuid:...` prefixed.

**Review by carlosthe19916 — CHANGES_REQUESTED** [review]
If I do `/api/v1/product/{id}` then I get something like:
```json
{
    "id": "urn:uuid:2f08a6c6-093b-4eb5-9b74-7eeae927ec9b",
    "name": "quarkus-bom",
    "versions": [
        {
            "id": "urn:uuid:89dae774-17c6-4f38-b6fa-92e04bb59988",
            "version": "3.2.6.Final-redhat-00002",
            "sbom_id": "0190a2fa-539f-7520-9754-11c41e05a7e1"
        },
        {
            "id": "urn:uuid:09f15558-7fbe-4bb7-8324-cf1bdee05a03",
            "version": "3.2.10.Final-redhat-00002",
            "sbom_id": "0190a2fa-5c4a-7710-9870-6a262d3ed410"
        },
        {
            "id": "urn:uuid:4e6543f7-a425-4bdf-9921-8e21be97823a",
            "version": "2.13.9.Final-redhat-00004",
            "sbom_id": "0190a2fa-6440-7ba2-b5fd-cf721b5a8531"
        },
        {
            "id": "urn:uuid:e6da61ab-ac1a-425c-ab3e-c090cc52a05b",
            "version": "3.2.9.Final-redhat-00004",
            "sbom_id": "0190a2fa-6d60-7721-92c1-ed0c5de5974c"
        },
        {
            "id": "urn:uuid:0eefb51d-b76a-4368-9198-55a9b809531b",
            "version": "3.2.11.Final-redhat-00001",
            "sbom_id": "0190a2fa-75af-77b1-b66a-d59f12e373f5"
        },
        {
            "id": "urn:uuid:0a37d78c-3c1d-4ab1-9f22-ede79e702939",
            "version": "3.2.12.Final-redhat-00002",
            "sbom_id": "0190a2fa-7da4-7462-b79f-126ce3f413ce"
        },
        {
            "id": "urn:uuid:f8967d20-08c4-46a9-95a9-5d605ad7d4d1",
            "version": "3.2.9.Final-redhat-00003",
            "sbom_id": "0190a2fa-8649-7513-a344-4eb48e71ad26"
        },
        {
            "id": "urn:uuid:35d1d15c-5cde-46a3-a5f0-befa116bfe11",
            "version": "2.13.8.SP3-redhat-00001",
            "sbom_id": "0190a2fa-8f00-7821-8793-981d79a9e5de"
        }
    ],
    "vendor": {
        "id": "87026ca9-5860-4caa-a41a-4ac9c69c60d2",
        "name": "Organization: Red Hat"
    }
}
```

Notice that the `sbom_id` fields are something like `0190a2fa-539f-7520-9754-11c41e05a7e1` and they miss their prefixes.

I can not take the `sbom_id` as they are now because the endpoint `/api/v1/sbom/{id}` requires a prefix and IDs without prefix are not accepted

**Review by dejanb — APPROVED** [review]
Looks good

**Review by carlosthe19916 — APPROVED** [review]
Thanks for the enhancement guys!

**Pull request merged**
