### PR TITLE
Provide searching for base versionless and fully-qualified packages u…

### PR DESCRIPTION
**Pull request by bobmcwhirter**
…sing `?q=`.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
@carlosthe19916 still [draft] but here's a shot at supporting `?q=` on `/api/v1/package` and `/api/v1/package/base` depending on how wide a given search wants to be.

I suspect I don't have sorting right yet.

**Review by carlosthe19916 — APPROVED** [review]
I confirm `GET /api/v1/package` works now and gives back a list of packages.
This is a very good first step let's merge it once you are ready.

If there are things I discovered are missing like sorting, filtering, etc, I can create issues.

**Comment by carlosthe19916** [comment]
One thing that I will probably request on another gh_issue is to support appropriate filtering on `GET /api/v1/package?q=...`. I appreciate we have multiple endpoints at the moment, but the client will use the filtering query parameters for searching "by type", "by namespace", "etc". But first things first, let's have this done and then we can discuss what to do next

image

**Comment by bobmcwhirter** [comment]
I'd hope filters would work already. It's using our standard Query magic from Jim.

**Comment by carlosthe19916** [comment]
Cool. Looking forward to see this PR merged!

**Comment by bobmcwhirter** [comment]
Right on, added a test and indeed filtering by fields works as expected.

`    let uri = "/api/v1/package?q=type=maven";`

**Comment by carlosthe19916** [comment]
This PR has been approved. Whenever you are ready push the merge button :)

**Review by jcrossley3 — APPROVED** [review]

**Review by ctron — APPROVED** [review]

**Pull request merged**
