### PR TITLE
changed all the println to use log::info | debug

### PR DESCRIPTION
**Pull request by NoodleSamaChan**
Hello :)
This is my first PR on the project, please don't hesitate to let me know if anything is wrong with it!

fixes https://github.com/trustification/trustify/issues/43

### CODE REVIEW

**Comment by helio-frota** [comment]
hi @NoodleSamaChan thanks for this!

I found nice that you also changed the commented-code-parts :smile:  I was expecting this ( because there are some attempts/researches/etc and yeah probably not good to delete commented code at this point)  but I forgot to add on the issue description :facepalm: 

In the spirit-of-sync-things ... I'll approve your PR but let's wait a bit ( for others opinion / availability )



Since we have other PR with a thing related to logs so that we can see if we need to rebase / we can experiment locally / etc

**Review by helio-frota — APPROVED** [review]

**Comment by helio-frota** [comment]
Added @bobmcwhirter since the other PR was marked as a draft

**Comment by helio-frota** [comment]
@NoodleSamaChan could you please fix the cargo fmt to make CI happy ? thanks

Interestingly vscode is showing nothing to me :+1: 



After (control + shift + i) format it fix what CI is complaining

**Comment by ctron** [comment]
Not sure what vscode does. IntelliJ (and friends like Rust Rover) do apply internal formatter by default. You can switch to `cargo fmt` in the settings.

Ultimately, just run `cargo fmt`.

**Comment by helio-frota** [comment]
@NoodleSamaChan Thank you very much for your contribution!

**Pull request merged**
