### PR TITLE
don't add primary key ORDER BY clause when GROUP BY is present

### PR DESCRIPTION
**Pull request by jcrossley3**
Fixes: #291

### CODE REVIEW

**Comment by jcrossley3** [comment]
> So if I would filter for "GROUP BY", the sorting would be gone?

Yes. Without having access to the statement's internals, I'm not sure how to distinguish the text in the filter from an actual GROUP BY clause.

So maybe we don't need this PR. Because all the Entity's columns need to be included in the GROUP BY clause anyway.

**Comment by ctron** [comment]
> So maybe we don't need this PR. Because all the Entity's columns need to be included in the GROUP BY clause anyway.

Maybe, taking the following example: https://github.com/trustification/trustify/blob/0d0d5a414f058570d841ed50b5544d2378db2290/modules/fetch/src/service/sbom.rs#L131-L145

The `sbom_id` is part of the primary key, but doesn't need to be returned, so it's not selected.

Technically, it could be added. But that would mean that whenever someone wants to use filtering, the statements have the crafted in way that they select all PKs and group them. Because: just in case.

**Comment by jcrossley3** [comment]
The only reason the primary key ordering is added is to maintain consistent paginated results. Do we really need that? Is there a better way? I'm open to ideas.

**Comment by ctron** [comment]
> The only reason the primary key ordering is added is to maintain consistent paginated results. Do we really need that? Is there a better way? I'm open to ideas.

that's actually an aspect of the "limiter". So I would say it shouldn't be a concern for search.

Search might override those settings.

**Comment by jcrossley3** [comment]
How does the limiter ensure the ordering? Isn't it possible the same item might appear in multiple batches?

**Comment by ctron** [comment]
> How does the limiter ensure the ordering? Isn't it possible the same item might appear in multiple batches?

It doesn't. It requires you have a stable order. That's why in most (if not all) there is an explicit order statement. Because only the query know what might make sense as a default order.

**Comment by jcrossley3** [comment]
Ok, cool. I'm happy to assume the callers of `.filtering` will ensure the stable order. That'll simplify a lot!

**Comment by jcrossley3** [comment]
I added the fix to #299 in order to avoid rebase conflicts do to the new names.

**Pull request closed without merging**
