### PR TITLE
chore: using local time for PM-mode

### PR DESCRIPTION
**Pull request by helio-frota**
Related to #239

### CODE REVIEW

**Comment by helio-frota** [comment]
```console
2024-05-07T08:24:27.486380625-03:00  INFO actix_server::accept: accept thread stopped
2024-05-07T08:24:27.486452376-03:00  INFO actix_server::worker: shutting down idle worker
2024-05-07T08:24:27.486502522-03:00  INFO actix_server::worker: shutting down idle worker
➜  trustify git:(localtime) date
Tue May  7 08:24:29 AM -03 2024
```

**Comment by ctron** [comment]
Hm, I am unsure about this.

For PM mode, that might make sense.

For actual deployments, using UTC in any case makes more sense. Because otherwise it will become pretty hard to correlate events.

I am ok adding this. I am also ok having this as a default when launching from the command line. But I think there should be some "UTC log timestamps" switch.

**Comment by helio-frota** [comment]
yeah makes no sense for deployments.

thanks for the extras :+1: 

I got what you mean.. `init_no_tracing` is not only for PM-mode... which may end up deploying with disable traces and not using UTC. that is bad.

**Comment by helio-frota** [comment]
>  But I think there should be some "UTC log timestamps" switch.

yes, or even better way of think about this --> a local (PM-mode) and server (deployment) something-that-we-can-switch

**Comment by helio-frota** [comment]
**question:** currently it is only possible to enable traces (programmatically) via compiled code ?

if yes I'm ok :+1:

**Comment by helio-frota** [comment]
**note:** keeping your previous comment in mind I'm not OK with this PR.

```
There are two variants, one when "tracing" is enabled, and all information is sent to an opentelemetry endpoint (in which case there's no logging on the console).

Or when "tracing" it not enabled, then everything goes to the console....
```

Please correct me if I'm wrong, we have the following:

a) deployment :heavy_check_mark: 
b) deployment with traces :heavy_check_mark: 
c) pm-mode :heavy_check_mark: 
d) pm-mode with traces - is a thing that makes no sense other than for DEV purposes ( to check if things are working fine with traces etc ) :no_entry_sign:


So with this PR we fix **c)** and break **a)**

**Comment by ctron** [comment]
Yes, I think that sums it up. "PM mode with tracing" is nothing we should focus on.

I guess having a simple `--force-utc-logs` might work.

**Comment by helio-frota** [comment]
TBQH I'm more in favor of closing this PR and the related issue, than adding functionality that probably no one will use.

**Pull request closed without merging**
