### PR TITLE
Make PM mode the default

### PR DESCRIPTION
**Pull request by jcrossley3**
Also removing `ui` feature as I think it's just static content now.

### CODE REVIEW

**Review by bobmcwhirter — APPROVED** [review]

**Review by helio-frota — APPROVED** [review]

**Comment by ctron** [comment]
I would ask that you create another release in a personal fork to validate that the outcome is as expected.

**Comment by jcrossley3** [comment]
> I would ask that you create another release in a personal fork to validate that the outcome is as expected.

No clue how to do that or what to expect.

**Comment by helio-frota** [comment]
> No clue how to do that 

probably **?**:

git push **origin** v0.1.1-alpha-foobar.2  

instead of 

git push **upstream** v0.1.1-alpha-foobar.2 

https://github.com/trustification/trustify/blob/main/RELEASE.md#trigger-the-release

it generates releases in personal fork  https://github.com/helio-frota/rgold/actions

**Comment by helio-frota** [comment]
I'm not getting this part yet ( the error part ) https://github.com/helio-frota/trustify/actions/runs/9372621600
I'll try with other version to see what happens

**Comment by helio-frota** [comment]
I think I got the error part:
a) cargo release version alpha 
b) cargo release version alpha -x
c) git commit -a -m "chore: A Foo Bar thing only"
d) trustify git:(pm-default) git tag v0.1.0-alpha.6 pm-default
e) git push origin v0.1.0-alpha.6

it is working at least https://github.com/helio-frota/trustify/actions/runs/9372893743

**Pull request merged**
