### PR TITLE
chore: remove unused things

### PR DESCRIPTION
**Pull request by helio-frota**
* focusing on graph dir only

Related to #17

### CODE REVIEW

**Review by jcrossley3 — CHANGES_REQUESTED** [review]
This is doing a lot more than just "removing unused things". Let's start by just removing all the unused imports.

I'm curious, though: what's the reason for all the `#[allow(dead_code)]` and `TODO` comments?

**Comment by helio-frota** [comment]
Reading again the issue I got the thing... we are not kind of prepared to remove this part `#![allow(unused)]` yet... 

I'll add back `#![allow(unused)]` and revert the other changes :+1:

**Comment by helio-frota** [comment]
@jcrossley3 PR updated :+1:

**Review by jcrossley3 — APPROVED** [review]
Thank you!

**Comment by helio-frota** [comment]
@jcrossley3 thanks!

**Pull request merged**
