### PR TITLE
chore: enable metrics endpoint

### PR DESCRIPTION
**Pull request by helio-frota**
Related to https://github.com/trustification/trustify/discussions/262
Sort of related to #261 

```sh
➜  ~ curl http://localhost:8080/metrics
# HELP trustify_http_requests_duration_seconds HTTP request duration in seconds for all requests
# TYPE trustify_http_requests_duration_seconds histogram
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.005"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.01"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.025"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.05"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.1"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.25"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="0.5"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="1"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="2.5"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="5"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="10"} 1
trustify_http_requests_duration_seconds_bucket{endpoint="/metrics",method="GET",status="200",le="+Inf"} 1
trustify_http_requests_duration_seconds_sum{endpoint="/metrics",method="GET",status="200"} 0.000127021
trustify_http_requests_duration_seconds_count{endpoint="/metrics",method="GET",status="200"} 1
# HELP trustify_http_requests_total Total number of HTTP requests
# TYPE trustify_http_requests_total counter
trustify_http_requests_total{endpoint="/metrics",method="GET",status="200"} 1
```

### CODE REVIEW

**Review by jcrossley3 — COMMENTED** [review]
Does this get rid of the swagger-ui "mixed cardinality" warning in the log?

**Comment by helio-frota** [comment]
No, I noticed that is apparently another thing from https://github.com/nlopes/actix-web-prom

But it excludes the track/collecting-metrics from those paths 
https://github.com/trustification/trustify/issues/261#issuecomment-2108509183

**Comment by jcrossley3** [comment]
> But it excludes the track/collecting-metrics from those paths [#261 (comment)](https://github.com/trustification/trustify/issues/261#issuecomment-2108509183)

Why don't we want them in our metrics?

**Comment by helio-frota** [comment]
/me closing In the light of 

* I don't know if we need this right now
* Already know how to see the metrics to make experiments
* It is possible to exclude paths 
* And we have a better specific issue related to log warning https://github.com/trustification/trustify/issues/302

**Pull request closed without merging**
