### PR TITLE
Add report to source_document meta

### LINKED ISSUE #896: SBOM quality reporting
Valid SBOMs can have a range of issues; missing pURLs, missing or invalid licenses, or just 'garbage' data. Ingesting such SBOMs can often lead to surprising results which we should minimally at least be able to report on.

Existing [reporting](https://github.com/trustification/trustify/blob/d7ac13374432a964b4d6140b8cbe5cfc506f223f/modules/ingestor/src/graph/sbom/spdx.rs#L306) should be improved to be able to 'score' an SBOM's quality and make explicit so end users can assess risk properly.

Towards this goal - developing a small, focused [utility](https://github.com/JimFuller-RedHat/sbomsleuth) that we can consider adding as a dep to trustify.

### PR DESCRIPTION
**Pull request by JimFuller-RedHat**
Generate [sbomsleuth](https://github.com/JimFuller-RedHat/sbomsleuth) report when ingesting sbom which fixes #896

We will need to discuss where this report data is exposed .. possibly on **api/v1/sbom** endpoints ?

### CODE REVIEW

**Comment by ctron** [comment]
I think the idea is good. But what I don't like is that we now have two "reports". One from sbomsleuth, the other existing report. And that we seem to have two different ways dealing with them.

I'd prefer if we could merge the sbomsleuth report and the `warnings` in a single thing. Which we collect in the importer run report, report back on the API, and store in the source document table.

**Comment by JimFuller-RedHat** [comment]
sure one thing better then two ;)

The importer run report does not currently work on any sboms uploaded via rest api (or maybe I missed it?) ... I was hoping to get some direction on unifying on that axis as well.

Also - do we want to 'bake in' heuristics on reports in trustify or push that to some calling client to decide (and maintain) ? 

Sounds like we need to discuss further.

**Comment by ctron** [comment]
image

**Comment by ctron** [comment]
:rofl: Let's have a chat.

**Pull request closed without merging**
