### PR TITLE
fix: able to run pm-mode in container

### PR DESCRIPTION
**Pull request by helio-frota**
Related to https://github.com/trustification/trustify/issues/725

```console
➜  trustify git:(minimal) ✗ podman run -it ff9a6186871e
RUST_LOG is unset, using default: 'info,actix_web_prom=error'
2024-09-05T20:12:41.391532Z  WARN trustd::db: Setting up managed DB; not suitable for production use!
2024-09-05T20:13:01.569275Z  INFO trustd::db: PostgreSQL installed in "/usr/local/bin/.trustify/postgres"
2024-09-05T20:13:01.569318Z  INFO trustd::db: Running on port 45587
2024-09-05T20:13:01.601705Z  INFO bootstrap: sqlx::postgres::notice: database "trustify" does not exist, skipping database=Database { username: "postgres", password: "trustify", host: "localhost", port: 45587, name: "trustify", max_conn: 75, min_conn: 25 }
2024-09-05T20:13:01.601756Z  INFO bootstrap: sqlx::query: summary="DROP DATABASE IF EXISTS …" db.statement="\n\nDROP DATABASE IF EXISTS \"trustify\";\n" rows_affected=0 rows_returned=0 elapsed=403.995µs elapsed_secs=0.000403995 database=Database { username: "postgres", password: "trustify", host: "localhost", port: 45587, name: "trustify", max_conn: 75, min_conn: 25 }
2024-09-05T20:13:01.639588Z  INFO bootstrap: sqlx::query: summary="CREATE DATABASE \"trustify\";" db.statement="" rows_affected=0 rows_returned=0 elapsed=28.721674ms elapsed_secs=0.028721674 database=Database { username: "postgres", password: "trustify", host: "localhost", port: 45587, name: "trustify", max_conn: 75, min_conn: 25 }
2024-09-05T20:13:01.863348Z  INFO bootstrap:migrate: sea_orm_migration::migrator: Applying all pending migrations database=Database { username: "postgres", password: "trustify", host: "localhost", port: 45587, name: "trustify", max_conn: 75, min_conn: 25 } self=Database { db: SqlxPostgresPoolConnection, name: "trustify" }
...
...
```

### CODE REVIEW

**Comment by helio-frota** [comment]
easy way to reproduce

from project root dir (copy/pasta):

```
./.github/scripts/dev-build.sh 0.1.0-alpha.14
```

copy the first image id in:

```
podman image list
```

run

```
podman run -it image_id_here
```

**Comment by helio-frota** [comment]
> Maybe it makes more sense, having an additional "pm" container?!

I'm +1 for it -- I understand a `pm-container` as a way to have a `pre-compiled-tag-based-easy-to-run-without-rust-installed-locally-pm-mode` , which I agree that makes no much sense to be part of a "production" container

**Comment by helio-frota** [comment]
PR updated adding a new file with .pmmode extension ( .pm extension my neovim thinks it is a perl module )

**Review by ctron — APPROVED** [review]

**Comment by jcrossley3** [comment]
Why do we need this? Who or what will consume `Containerfile.pmmode` @ctron ?

**Pull request merged**
