### PR TITLE
Add a first re-ingest test, fix issues discovered by doing that

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Review by bobmcwhirter — COMMENTED** [review]
Reading the comments, I see the "problem" that two versions act like two sboms. 

I'm unclear if this PR somehow unifies them, or if it maintains them as two distinct SBOMs.

I think we decided they stay two distinct SBOMs, both available for the thing they describe? Perhaps sorted by... date? serial number? so we can see evolution over time if a vendor re-issues against the same SBOM repeatedly?

**Comment by ctron** [comment]
The PR currently only tests the status quo. It should not change the behavior. Two different files will end up in two different SBOMs. Unless their are actual (byte-by-byte) copies.

Also see the discussion: #453

**Comment by bobmcwhirter** [comment]
Excellent, that's the behaviour I was expecting/hoping for.

**Review by bobmcwhirter — APPROVED** [review]

**Comment by ctron** [comment]
Merged as part of #452

**Pull request closed without merging**
