### PR TITLE
test: tests trustify-cli help

### PR DESCRIPTION
**Pull request by helio-frota**
* Adds pretty_assertions as dev-dependency for easy cli-diff-tests-results visualization

### CODE REVIEW

**Comment by helio-frota** [comment]
/me trying to fix vscode that failed with fmt and clippy :+1:

**Comment by helio-frota** [comment]
motivations/reasons I found:

* pretty_assertions as `dev-dependency` will not hurt (in case used) but we can remove it, not required 
* cargo-llvm-cov ignores `tests` hard-coded
* the result of the coverage tests makes more sense ( see screenshots )
* avoid big files, separating tests in different files
* I learned separated tests on `Command-Line Rust` book :D

**Review by bobmcwhirter — COMMENTED** [review]
I'm not sure testing for textual output at this level is overly beneficial, but I'd welcome others' thoughts.

Some test strategy (or lint?) ensuring that everything has some description in the Clap structures/derives, mayhap more useful.

e.g., we don't really care the exact wording, test-wise, but we *do* care that we're not leaving big empty holes which should have some documentation/words in them.

**Comment by ctron** [comment]
I 100% agree with that: https://github.com/trustification/trustify/pull/21#pullrequestreview-1925002592

**Comment by helio-frota** [comment]
thanks for the feedback !

I also agree with the comments about the test-function-it-self :+1: 

The most important parts for me in this PR are:

* `tests` directory to satisfy the coverage tool
* the (optional) pretty_assertions dev-dependency

**Comment by helio-frota** [comment]
Thanks all for the extra info!

**Pull request closed without merging**
