### PR TITLE
Bring back /api/v1/vulnerability/ and /api/v1/vulnerability/{identifi…

### PR DESCRIPTION
**Pull request by bobmcwhirter**
…er}.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Do not merge. I have more thoughts.

**Comment by bobmcwhirter** [comment]
Head. Summary. Details. Note to self.

**Review by ctron — APPROVED** [review]

**Comment by ctron** [comment]
Tracking issue for missing digests: https://github.com/trustification/trustify/issues/217

**Review by ctron — APPROVED** [review]
I see a lot of dead (?) code. But I assume we can kill or revive that later.

**Pull request merged**
